### ISSUE TITLE
[Bug]: workflows with large `strides` fail on the `fill_ps` stage

### ISSUE THREAD

**Issue by scottstanie** [opera-adt/dolphin#18]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

For larger striding windows, the s1_disp workflow is failing here:

```
  File "/u/aurora-r0/staniewi/repos/dolphin/src/dolphin/phase_link/mle.py", line 319, in _fill_ps_pixels
    mle_est[i][fill_mask] = slc_stack[i][slc_r_idxs, slc_c_idxs] * ref
ValueError: NumPy boolean array indexing assignment cannot assign 595 input values to the 596 output values where the mask is true
```

**Comment by scottstanie** [comment]
Traceback (most recent call last):
  File "/u/aurora-r0/staniewi/miniconda3/envs/mapping/bin/dolphin", line 8, in <module>
    sys.exit(main())
  File "/u/aurora-r0/staniewi/repos/dolphin/src/dolphin/cli.py", line 22, in main
    run_func(**arg_dict)
  File "/u/aurora-r0/staniewi/repos/dolphin/src/dolphin/_log.py", line 94, in wrapper
    result = f(*args, **kwargs)
  File "/u/aurora-r0/staniewi/repos/dolphin/src/dolphin/workflows/_run_cli.py", line 26, in run
    s1_disp_stack.run(cfg, debug=debug)
  File "/u/aurora-r0/staniewi/repos/dolphin/src/dolphin/_log.py", line 94, in wrapper
    result = f(*args, **kwargs)
  File "/u/aurora-r0/staniewi/repos/dolphin/src/dolphin/workflows/s1_disp_stack.py", line 61, in run
    cur_ifg_list = wrapped_phase.run(burst_cfg, debug=debug)
  File "/u/aurora-r0/staniewi/repos/dolphin/src/dolphin/_log.py", line 94, in wrapper
    result = f(*args, **kwargs)
  File "/u/aurora-r0/staniewi/repos/dolphin/src/dolphin/workflows/wrapped_phase.py", line 71, in run
    sequential.run_evd_sequential(
  File "/u/aurora-r0/staniewi/repos/dolphin/src/dolphin/sequential.py", line 175, in run_evd_sequential
    )
  File "/u/aurora-r0/staniewi/repos/dolphin/src/dolphin/phase_link/mle.py", line 155, in run_mle
    _fill_ps_pixels(
  File "/u/aurora-r0/staniewi/repos/dolphin/src/dolphin/phase_link/mle.py", line 322, in _fill_ps_pixels
    mle_est[i][fill_mask] = slc_stack[i][slc_r_idxs, slc_c_idxs] * ref
ValueError: NumPy boolean array indexing assignment cannot assign 8184 input values to the 8183 output values where the mask is true
