### ISSUE TITLE
Singular matrix error for CPU workflow

### ISSUE THREAD

**Issue by scottstanie** [opera-adt/dolphin#43]
From @taliboliver 's testing:

```python traceback
[02/08 13:44:16] [INFO s1_disp_stack.py] Running wrapped phase estimation
[02/08 13:44:16] [INFO wrapped_phase.py] Creating persistent scatterer file /mnt/aurora-r0/cabrera/data/compass_test/scratch/PS/ps_pixels.tif
100%|███████████████████████████████████████████████████████████████████████████████████| 12/12 [01:01<00:00,  5.14s/it]
[02/08 13:45:19] [INFO ps.py] Waiting to write 0 blocks of data.
[02/08 13:45:19] [INFO ps.py] Finished writing out PS files
[02/08 13:45:19] [INFO wrapped_phase.py] Running sequential EMI step in /mnt/aurora-r0/cabrera/data/compass_test/scratch/linked_phase
[02/08 13:45:20] [INFO sequential.py] VRTStack(19 bands, outfile=/mnt/aurora-r0/cabrera/data/compass_test/scratch/slc_stack.vrt): from /mnt/aurora-r0/cabrera/data/compass_test/stack/t013_026559_iw1/20210601/t013_026559_iw1_20210601_VV.h5 to /mnt/aurora-r0/cabrera/data/compass_test/stack/t013_026559_iw1/20211222/t013_026559_iw1_20211222_VV.h5
[02/08 13:45:20] [INFO sequential.py] Processing 15 files + 0 compressed. Output folder: /mnt/aurora-r0/cabrera/data/compass_test/scratch/linked_phase/20210601_20211104
[02/08 13:45:21] [INFO sequential.py] VRTStack(15 bands, outfile=/mnt/aurora-r0/cabrera/data/compass_test/scratch/linked_phase/20210601_20211104/20210601_20211104.vrt): from t013_026559_iw1_20210601_VV.h5 to t013_026559_iw1_20211104_VV.h5
 11%|████████▊                                                                         | 20/185 [00:09<01:20,  2.06it/s]Traceback (most recent call last):
  File "/home/cabrera/python/miniconda3/envs/opera/bin/dolphin", line 8, in <module>
    sys.exit(main())
  File "/home/cabrera/python/miniconda3/envs/opera/lib/python3.9/site-packages/dolphin/cli.py", line 22, in main
    run_func(**arg_dict)
  File "/home/cabrera/python/miniconda3/envs/opera/lib/python3.9/site-packages/dolphin/_log.py", line 94, in wrapper
    result = f(*args, **kwargs)
  File "/home/cabrera/python/miniconda3/envs/opera/lib/python3.9/site-packages/dolphin/workflows/_run_cli.py", line 26, in run
    s1_disp_stack.run(cfg, debug=debug)
  File "/home/cabrera/python/miniconda3/envs/opera/lib/python3.9/site-packages/dolphin/_log.py", line 94, in wrapper
    result = f(*args, **kwargs)
  File "/home/cabrera/python/miniconda3/envs/opera/lib/python3.9/site-packages/dolphin/workflows/s1_disp_stack.py", line 61, in run
    cur_ifg_list = wrapped_phase.run(burst_cfg, debug=debug)
  File "/home/cabrera/python/miniconda3/envs/opera/lib/python3.9/site-packages/dolphin/_log.py", line 94, in wrapper
    result = f(*args, **kwargs)
  File "/home/cabrera/python/miniconda3/envs/opera/lib/python3.9/site-packages/dolphin/workflows/wrapped_phase.py", line 71, in run
    sequential.run_evd_sequential(
  File "/home/cabrera/python/miniconda3/envs/opera/lib/python3.9/site-packages/dolphin/sequential.py", line 165, in run_evd_sequential
    cur_mle_stack, tcorr = run_mle(
  File "/home/cabrera/python/miniconda3/envs/opera/lib/python3.9/site-packages/dolphin/phase_link/mle.py", line 125, in run_mle
    mle_est, temp_coh = _run_cpu(
  File "/home/cabrera/python/miniconda3/envs/opera/lib/python3.9/site-packages/dolphin/phase_link/_mle_cpu.py", line 66, in run_cpu
    output_phase = mle_stack(C_arrays, beta, reference_idx)
  File "/home/cabrera/python/miniconda3/envs/opera/lib/python3.9/site-packages/dolphin/phase_link/mle.py", line 208, in mle_stack
    Gamma_inv = xp.linalg.inv(Gamma)
  File "<__array_function__ internals>", line 180, in inv
  File "/home/cabrera/python/miniconda3/envs/opera/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 552, in inv
    ainv = _umath_linalg.inv(a, signature=signature, extobj=extobj)
  File "/home/cabrera/python/miniconda3/envs/opera/lib/python3.9/site-packages/numpy/linalg/linalg.py", line 89, in _raise_linalgerror_singular
    raise LinAlgError("Singular matrix")
numpy.linalg.LinAlgError: Singular matrix
```

This is not happening for the GPU workflow. Numpy is louder with it's erroring for inversion than `cupy` is.

**Comment by scottstanie** [comment]
This was happening here from one eigenvalue that was -2e-7:
```python traceback
ipdb> np.linalg.eigh(Gamma[55, 1107] * C_arrays[55, 1107])[0]
array([-2.1234169e-07,  5.1951128e-01,  9.0359849e-01,  9.2329526e-01,
        9.5432651e-01,  9.8514080e-01,  1.0000000e+00,  1.0000000e+00,
        1.0000000e+00,  1.0000000e+00,  1.0000000e+00,  1.0000000e+00,
        1.0000000e+00,  1.0000000e+00,  1.0172563e+00,  1.0392334e+00,
        1.0573467e+00,  1.1158751e+00,  2.4844165e+00], dtype=float32)
```

In the test run of the fix in #44, the error goes away.
